# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: 소개
    url: about/
    weight: 20
  - name: 매뉴얼
    url: docs/
    weight: 30
#  - name: Blog
#    url: blog/
#    weight: 30
  - name: 프로그램
    url: showcase/
    weight: 40

sidebar:
  - identifier: more
    name: Still need help?
    params:
      type: separator
    weight: 1
  - identifier: community
    name: "Community"
    pageRef: "/community"
    weight: 2
  - identifier: hugoDocs
    name: "Hugo Docs ↗"
    url: ""
    weight: 3
