# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: 포트폴리오
    url: portfolio/
    weight: 30
  - name: 문서
    url: docs/
    weight: 40
  - name: 블로그
    url: blog/
    weight: 50
  - name: About
    url: about/
    weight: 60

sidebar:
  - identifier: more
    name: More
    params:
      type: separator
    weight: 1
  - identifier: github
    name: "GitHub ↗"
    url: "https://github.com/suecreamm"
    weight: 2
