# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: 문서
    url: docs/
    weight: 30
  - name: 블로그
    url: blog/
    weight: 40
  - name: 프로젝트
    url: projects/
    weight: 50
  - name: About
    url: about/
    weight: 60

sidebar:
  - identifier: more
    name: Still need help?
    params:
      type: separator
    weight: 1
