# Appearance
appearance:
  mode: light
  color: blue

# SEO
marketing:
  seo:
    site_type: Project
    local_business_type: 'Research'
    org_name: 'Suecreamm'
    description: 'Shares physics-related topics from my PhD studies' 
    twitter: ''
  analytics:
    google_analytics: ''
    google_tag_manager: ''
    microsoft_clarity: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    align: "center"
    fixed_to_top: true
    logo:
      text: "Sue's Thread"
      # Logo filename in `assets/media/` folder
      filename: "" #"logo.svg"
    button:
      enable: false
      text: "Get Started"
      url: "https://hugoblox.com/templates/details/docs/"
    show_search: true
    show_theme_chooser: true

# Site footer
footer:
  copyright:
    notice: '© {year} Suecreamm. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: true
  privacy_pack:
    enable: false
  repository:
    url: ''
    content_dir: 'starters/documentation/content'
    branch: 'main'
  feedback:
    responses:
      positive: 'Glad to hear it! [Any ideas for improvements?](https://github.com/<USERNAME>/<REPO>/issues/new).'
      negative: 'Sorry to hear that. [Please tell us how we can improve](https://github.com/<USERNAME>/<REPO>/issues/new).'
  comment:
    provider: 'giscus'
    giscus:
      repo: 'suecreamm/suecreamm.github.io'
      repo_id: 'R_kgDOLeN49Q'
      category: 'Announcements'
      category_id: 'DIC_kwDOLeN49c4Cd60Y'

# Extensions
extensions:
  academicons:
    enable: true
  fontawesome:
    enable: true
  fas:
    enable: true
  


# CMS
#extensions:
#  decap_cms:
#    branch: main
#     publish_mode: editorial_workflow
#     local_backend: true
