[build]
  publish = "public"
  command = "hugo --gc --minify -b $URL && npx pagefind --source 'public'"

[build.environment]
  HUGO_VERSION = "0.122.0"
  HUGO_ENABLEGITINFO = "true"
  GO_VERSION = "1.21.0"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = true
